import containerQueries from '@tailwindcss/container-queries';

/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        canvas:           'var(--color-canvas)',
        surface:          'var(--color-surface)',
        'surface-2':      'var(--color-surface-2)',
        'surface-3':      'var(--color-surface-3)',
        line:             'var(--color-line)',
        'line-strong':    'var(--color-line-strong)',
        'text-primary':   'var(--color-text-primary)',
        'text-secondary': 'var(--color-text-secondary)',
        'text-muted':     'var(--color-text-muted)',
        'text-disabled':  'var(--color-text-disabled)',
        overlay:          'var(--color-overlay)',
        'overlay-soft':   'var(--color-overlay-soft)',
        'overlay-strong': 'var(--color-overlay-strong)',
        glass:            'var(--color-glass-panel)',
        'glass-line':     'var(--color-glass-border)',
        accent:           'var(--color-accent)',
        'accent-hover':   'var(--color-accent-hover)',
        'accent-soft':    'var(--color-accent-soft)',
        'accent-muted':   'var(--color-accent-muted)',
        'on-accent':      'var(--color-on-accent)',
        success:          'var(--color-success)',
        'success-soft':   'var(--color-success-soft)',
        danger:           'var(--color-danger)',
        'danger-soft':    'var(--color-danger-soft)',
        warn:             'var(--color-warn)',
        'warn-soft':      'var(--color-warn-soft)',
        info:             'var(--color-info)',
        'info-soft':      'var(--color-info-soft)',
        'space-orange':   '#f97316',
        'space-blue':     '#3b82f6',
        'space-purple':   '#a855f7',
        'space-teal':     '#14b8a6',
        'space-rose':     '#f43f5e',
        'space-lime':     '#84cc16',
      },
      fontFamily: {
        sans: ['Aptos', 'Segoe UI Variable', 'Segoe UI', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'ui-monospace', 'monospace'],
      },
      fontSize: {
        'display':    ['24px', { lineHeight: '1.2',  fontWeight: '600' }],
        'heading':    ['18px', { lineHeight: '1.3',  fontWeight: '600' }],
        'subheading': ['14px', { lineHeight: '1.4',  fontWeight: '500' }],
        'body':       ['14px', { lineHeight: '1.5',  fontWeight: '400' }],
        'caption':    ['12px', { lineHeight: '1.5',  fontWeight: '400' }],
        'code':       ['13px', { lineHeight: '1.5',  fontWeight: '400' }],
      },
      spacing: {
        '4.5': '18px',
        '5.5': '22px',
        '7.5': '30px',
        '13':  '52px',
        '15':  '60px',
        '18':  '72px',
      },
      borderRadius: {
        'card':    '12px',
        'input':   '8px',
        'btn':     '8px',
        'pill':    '9999px',
        'modal':   '16px',
        'node':    '14px',
        'nav':     '8px',
      },
      boxShadow: {
        'card':     'var(--shadow-card)',
        'dropdown': 'var(--shadow-dropdown)',
        'modal':    'var(--shadow-modal)',
        'glow':     'var(--shadow-glow)',
      },
      keyframes: {
        'pulse-dot': {
          '0%, 100%': { opacity: '1' },
          '50%':      { opacity: '0.4' },
        },
        'slide-in-right': {
          '0%':   { transform: 'translateX(100%)' },
          '100%': { transform: 'translateX(0)' },
        },
        'slide-out-right': {
          '0%':   { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(100%)' },
        },
        'fade-in': {
          '0%':   { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'scale-in': {
          '0%':   { opacity: '0', transform: 'scale(0.96)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        'shimmer': {
          '0%':   { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
      },
      animation: {
        'pulse-dot':       'pulse-dot 1.5s ease-in-out infinite',
        'slide-in-right':  'slide-in-right 250ms ease-out',
        'slide-out-right': 'slide-out-right 200ms ease-in',
        'fade-in':         'fade-in 150ms ease',
        'scale-in':        'scale-in 180ms ease-out',
        'shimmer':         'shimmer 1.5s ease-in-out infinite',
      },
      transitionDuration: {
        '150': '150ms',
        '200': '200ms',
        '250': '250ms',
        '300': '300ms',
      },
    },
  },
  plugins: [containerQueries],
};
